# Generated by Django 2.0.2 on 2018-02-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='first',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='add',
            name='second',
            field=models.FloatField(),
        ),
    ]
